// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID       int64     `json:"id"`
	Owner    string    `json:"owner"`
	Currency string    `json:"currency"`
	Balance  int64     `json:"balance"`
	CreateAt time.Time `json:"create_at"`
}

type Entry struct {
	ID        int64         `json:"id"`
	AccountID sql.NullInt64 `json:"account_id"`
	// can negatieve or positive
	Amount   int64     `json:"amount"`
	CreateAt time.Time `json:"create_at"`
}

type Transfer struct {
	ID            int64         `json:"id"`
	FromAccountID sql.NullInt64 `json:"from_account_id"`
	ToAccountID   sql.NullInt64 `json:"to_account_id"`
	// can not negative
	Amount   int64     `json:"amount"`
	CreateAt time.Time `json:"create_at"`
}
